# Generated by Django 5.0.2 on 2024-02-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCMPCChile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
