# Generated by Django 5.0.2 on 2024-02-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_registroexcel_delete_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscmpcchile',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='datoscmpcchile',
            table='datoschile',
        ),
    ]
