# Generated by Django 5.0.2 on 2024-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_balneariolaja_balnearios_bosquesplata_bucalemu_buin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposNovos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'camposnovos',
            },
        ),
        migrations.CreateModel(
            name='Chillan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chillan',
            },
        ),
        migrations.CreateModel(
            name='Fabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fabi',
            },
        ),
        migrations.CreateModel(
            name='Guadalajara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'guadalajara',
            },
        ),
        migrations.CreateModel(
            name='Irapuato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'irapuato',
            },
        ),
        migrations.CreateModel(
            name='OfiConcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'oficoncepcion',
            },
        ),
        migrations.CreateModel(
            name='OfiTemuco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ofitemuco',
            },
        ),
        migrations.CreateModel(
            name='Peru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'peru',
            },
        ),
        migrations.CreateModel(
            name='PiraidoSul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'piraiosul',
            },
        ),
        migrations.CreateModel(
            name='Quilicura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'quilicura',
            },
        ),
        migrations.CreateModel(
            name='SanJose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.CharField(default='', max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('frecuencia', models.CharField(max_length=100)),
                ('procedimientos', models.TextField()),
                ('parametro_control', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sanjose',
            },
        ),
    ]
