# Generated by Django 5.0.2 on 2024-02-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_camposnovos_chillan_fabi_guadalajara_irapuato_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pudahuel',
            table='pudahuel',
        ),
    ]
