# Generated by Django 5.0.2 on 2024-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_pudahuel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chillan',
            name='area',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='chillan',
            name='dependencia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chillan',
            name='frecuencia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chillan',
            name='horario',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chillan',
            name='parametro_control',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cordillera',
            name='area',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cordillera',
            name='dependencia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cordillera',
            name='frecuencia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cordillera',
            name='horario',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cordillera',
            name='parametro_control',
            field=models.CharField(max_length=1000),
        ),
    ]
