# Generated by Django 5.0.2 on 2024-03-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_chillan_area_alter_chillan_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='piraidosul',
            table='piraidosul',
        ),
    ]
