# Generated by Django 5.0.2 on 2024-03-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_nota_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nota',
            table='Notas',
        ),
    ]
